### ISSUE TITLE
"xzy.tumblr.com is not a valid blog."

### ISSUE THREAD

**Issue by quasipickle** [nporteschaikin/peak#17]
What constitutes an invalid blog?  The blog I'm trying to access is a real URL, it's not private, and it has content.

Incidentally, the error message is missing a space between the blog name and "is not a valid blog", so it looks like:

**ERROR**: xyz.tumblr.comis not a valid blog.

**Comment by nporteschaikin** [comment]
Hi @quasipickle!  Thanks for your interest. Are you entering `xyz` or `xyz.tumblr.com`?

That spacing issue will be fixed in the next release.  Thanks for pointing it out.

**Comment by quasipickle** [comment]
xyz.tumblr.com

**Comment by nporteschaikin** [comment]
I think that's your issue.  Your configuration should simply contain the subdomain (`xyz`).  I'll fix that in a future release; for now, try it with just `xyz`.

**Comment by quasipickle** [comment]
Yep, that did it - thanks.
